### ISSUE TITLE
Question: clearing ability of TumbleBit protocol (cost reduction)

### ISSUE THREAD

**Issue by runeksvendsen** [BUSEC/TumbleBit#4]
Dear TumbleBit developers

I've skimmed the TumbleBit paper with excitement, and although it goes into great detail on the anonymity aspect of the TumbleBit protocol, I can't find any direct mentions of its ability to clear payments. That is, aggregating payments from multiple clients into a single receiver output in the blockchain, with the purpose of saving money on blockchain fees.

Let's say we have 10 clients connected to the same TumbleBit hub as a single merchant. Each of the clients make 10 payments of 0.01 BTC each to the merchant, totalling 100 payments with a sum value of 1.0 BTC (disregarding fees). Now, the merchant wants to redeem his Bitcoins. What will the settling Bitcoin transaction -- that's published to the network -- look like? Will it have 10 different outputs, one from each client, all paying to the merchant's address, or can payments from different clients be cleared into a single blockchain UTXO?

Also, what happens if one of the 10 clients wants to leave the hub prematurely, before the merchant wants to redeem? Can the value, sent by this client to the merchant, stay in the payment hub, while the client is paid back only the remaining, unspent balance in a Bitcoin transaction?

**Comment by NicolasDorier** [comment]
The blockchain will see one transaction, one output: the tumbler paying the merchant.

Maybe more transaction if receiving so much payment need to be done through several payment channel. (since it is uni directional, merchant will need to open a new channel one has been completely used)

**Comment by runeksvendsen** [comment]
Thank you for the quick reply. This is really interesting. I think I just need to read the paper carefully, and then I might return with more questions later.

**Comment by goldbe** [comment]
On Mon, Jan 9, 2017 at 7:53 AM, Rune K. Svendsen <notifications@github.com>
wrote:

> Let's say we have 10 clients connected to the same TumbleBit hub as a
> single merchant. Each of the clients make 10 payments of 0.01 BTC each to
> the merchant, totalling 100 payments with a sum value of 1.0 BTC
> (disregarding fees). Now, the merchant wants to redeem his Bitcoins. What
> will the settling Bitcoin transaction -- that's published to the network --
> look like? Will it have 10 different outputs, one from each client, all
> paying to the merchant's address, or can payments from different clients be
> cleared into a single blockchain UTXO?


If all payments were part of one run of the TumbleBit protocol then yes,
they have to be cashed out in a single on-blockchain transation. As Nicolas
said.

> Also, what happens if one of the 10 clients wants to leave the hub
> prematurely, before the merchant wants to redeem? Can the value, sent by
> this client to the merchant, stay in the payment hub, while the client is
> paid back only the remaining, unspent balance in a Bitcoin transaction?
>
The thing is, with TumbleBit, no one can leave the hub prematurely before
the TumbleBit epoch completes. Why? Because this would break the anonymity
properties of the scheme.  We need everyone to cash out at the exact same
time, because if they cash out early, they reduce the size of the anonymity
set for the other players.

See the paper, figure 2 and sections IV.A, VII.B

http://eprint.iacr.org/2016/575.pdf

Thanks,
Sharon

-- 
Sharon Goldberg
Computer Science, Boston University
http://www.cs.bu.edu/~goldbe

**Comment by NicolasDorier** [comment]
> The thing is, with TumbleBit, no one can leave the hub prematurely before
the TumbleBit epoch completes. 

This is true for the tumbler mode.

For the payment hub mode, not yet developped in NTumbleBit, users do not care as much, so we can imagine to be more relaxed.

For tumbler mode @runeksvendsen I think my nice diagrams will help you understand. https://github.com/NTumbleBit/NTumbleBit/wiki/Under-the-Hood
